name: shs-action

on:
  workflow_dispatch: 
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          path: "project" 
      
      - name: Print DB User and Password
        run: |
          echo "DB User: ${{ secrets.DB_USER }}"
          echo "DB Password: ${{ secrets.DB_PASSWORD }}"
          
      - name: Run SHS Analyser
        id: shs-analyser
        uses: isel-leic-shs/shs-action@main
        with:
          db_user: "dcclient"
          db_password: "dev02"
          connection_string: "jdbc:postgresql://4.tcp.eu.ngrok.io:15014/dependencycheck?currentSchema=public"
          shs_token: "adwad"
          
      - name: Print github information
        run: cat "${{ steps.shs-analyser.outputs.repository_info}}"

      - name: Upload the Dependency-Check report
        uses: actions/upload-artifact@v2
        with:
          name: dependency check-report
          path: "${{steps.shs-analyser.outputs.dependency_check_report}}"
